version: '3.5'

services:
  # PHP
  doctrine-resettable-em-bundle-php7:
    container_name: doctrine-resettable-em-bundle-php7
    build: ./docker/php
    volumes:
      - .:/srv/www:delegated
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
