services:
  _defaults:
    public: false
    autowire: false
    autoconfigure: false

  PixelFederation\DoctrineResettableEmBundle\DBAL\Connection\AliveKeeper: '@PixelFederation\DoctrineResettableEmBundle\DBAL\Connection\AggregatedAliveKeeper'

  PixelFederation\DoctrineResettableEmBundle\DBAL\ConnectionsHandler:
    arguments:
      $aliveKeeper: '@PixelFederation\DoctrineResettableEmBundle\DBAL\Connection\AliveKeeper'
    tags:
      - {name: pixelfederation_doctrine_resettable_em_bundle.app_initializer}

  PixelFederation\DoctrineResettableEmBundle\DBAL\Connection\AggregatedAliveKeeper:
    arguments:
      $aliveKeepers: [] # will be provided by the extension

  PixelFederation\DoctrineResettableEmBundle\DBAL\Connection\OptimizedAliveKeeper:
    arguments:
      $decorated: '@PixelFederation\DoctrineResettableEmBundle\DBAL\Connection\AggregatedAliveKeeper'

  PixelFederation\DoctrineResettableEmBundle\DBAL\Connection\SimpleAliveKeeper:
    abstract: true
    arguments:
      $connection: ~ #will be provided by the extension

  PixelFederation\DoctrineResettableEmBundle\DBAL\Connection\FailoverAware\FailoverAwareAliveKeeper:
    abstract: true
    arguments:
      $logger: '@logger'
      $connection: ~ #will be provided by the extension
      $connectionName: ~ #will be provided by the extension

  PixelFederation\DoctrineResettableEmBundle\ORM\EntityManagersHandler:
    arguments:
      $entityManagers: ~
    tags:
      - {name: pixelfederation_doctrine_resettable_em_bundle.app_terminator}
      - {name: pixelfederation_doctrine_resettable_em_bundle.app_initializer}

  PixelFederation\DoctrineResettableEmBundle\RequestCycle\Initializers:
    arguments: [!tagged 'pixelfederation_doctrine_resettable_em_bundle.app_initializer']
    tags:
      - {name: kernel.event_listener, event: kernel.request, method: initialize, priority: 1000000}

  PixelFederation\DoctrineResettableEmBundle\RequestCycle\Terminators:
    arguments: [!tagged 'pixelfederation_doctrine_resettable_em_bundle.app_terminator']
    tags:
      - {name: kernel.event_listener, event: kernel.terminate, method: terminate, priority: -1000000}
