services:
  _defaults:
    public: false
    autowire: false
    autoconfigure: false

  PixelFederation\DoctrineResettableEmBundle\Connection\AliveKeeper\AliveKeeper: '@PixelFederation\DoctrineResettableEmBundle\Connection\AliveKeeper\AggregatedAliveKeeper'

  PixelFederation\DoctrineResettableEmBundle\Connection\ConnectionsHandler:
    arguments:
      $aliveKeeper: '@PixelFederation\DoctrineResettableEmBundle\Connection\AliveKeeper\AliveKeeper'
    tags:
      - {name: pixelfederation_doctrine_resettable_em_bundle.app_initializer}

  PixelFederation\DoctrineResettableEmBundle\Connection\AliveKeeper\AggregatedAliveKeeper:
    arguments:
      $aliveKeepers: [] # will be provided by the extension

  PixelFederation\DoctrineResettableEmBundle\Connection\AliveKeeper\OptimizedAliveKeeper:
    arguments:
      $decorated: '@PixelFederation\DoctrineResettableEmBundle\Connection\AliveKeeper\AggregatedAliveKeeper'

  PixelFederation\DoctrineResettableEmBundle\DBAL\Connection\DBALAliveKeeper:
    abstract: true
    arguments:
      $connection: ~ #will be provided by the extension

  PixelFederation\DoctrineResettableEmBundle\Redis\Cluster\Connection\RedisClusterAliveKeeper:
    abstract: true
    arguments:
      $connectionName: ~ #will be provided by the extension
      $redis: ~ #will be provided by the extension
      $constructorArguments: ~ #will be provided by the extension
      $logger: '@logger' #will be provided by the extension
    tags:
      - { name: monolog.logger, channel: doctrine-resettable-em-bundle }

  PixelFederation\DoctrineResettableEmBundle\DBAL\Connection\FailoverAware\FailoverAwareAliveKeeper:
    abstract: true
    arguments:
      $logger: '@logger'
      $connection: ~ #will be provided by the extension
      $connectionName: ~ #will be provided by the extension
    tags:
      - { name: monolog.logger, channel: doctrine-resettable-em-bundle }

  PixelFederation\DoctrineResettableEmBundle\RequestCycle\Initializers:
    arguments: [!tagged 'pixelfederation_doctrine_resettable_em_bundle.app_initializer']
    tags:
      - {name: kernel.event_listener, event: kernel.request, method: initialize, priority: 1000000}
